### ISSUE TITLE
How to use this package in Docker environment ?

### ISSUE THREAD

**Issue by rspljayesh** [sunspikes/clamav-validator#49]
Hello ,

I am trying to use your package in the docker environment.

Is there any tutorial available?

Please help me.

**Comment by vigneshgurusamy** [comment]
@rspljayesh First of all, you can use this package in any php environment. Only the way of connecting the clamav might differ.

This is my partial docker-compose.yml file with clamav container from one of my project.

```yaml
version: '3'
services:
  php-fpm:
    build:
      context: ./php/fpm/8.0
    container_name: rapl-php-fpm
    volumes:
      - ${APP_PATH}:/var/www
    networks:
      - local-net
  clamav:
    image: mkodockx/docker-clamav:latest
    container_name: clamav-service
    networks:
      - local-net
networks:
  local-net:
    driver: bridge
```

You have to use TCP Socket (instead of unix socket) to connect with clamav from php container

```env
CLAMAV_PREFERRED_SOCKET=tcp_socket
CLAMAV_TCP_SOCKET=tcp://clamav:3310
```
